### PR TITLE
Added a button to initialize camera path from training views 

### PR DESCRIPTION
**Pull request by FlorisE**
Thanks again for your great work on this project.

I added a button to initialize camera paths from the training view camera positions.

We used it for example in our SII paper about "neural scanning" to create animations flying around objects: https://github.com/robocip-aist/sii_nerf_scans

Also it seems other people have requested this feature:
https://github.com/NVlabs/instant-ngp/discussions/506

### CODE REVIEW

**Comment by Tom94** [comment]
Hi, this is great, thank you. I've just two requests before hitting the merge button:
1. Could you rename the method to `add_training_views_to_camera_path` to make clearer what it does? There are other methods that add or modify cameras within `Testbed` and those all pertain to the loaded cameras directly and not the path.
2. Could you add spacing and curly braces according to the surrounding code style?

**Comment by FlorisE** [comment]
Hi, I changed spaces to tabs and renamed the function. I'm not sure about the curly braces, if there are any that need to be changed could you give the location?

**Comment by Tom94** [comment]
The formatting looks good enough to me now. No worries.

I notices one more thing, though, and that's the position of the button. Could you move it such that it's next to the other training view widgets? I'm thinking between the following two rows would look good.
image

**Comment by Tom94** [comment]
Perfect, thank you!

**Pull request merged**
