### PR TITLE
Depth groundtruth render

### PR DESCRIPTION
**Pull request by jc211**
Added ability to render groundtruth depth. 
image

### CODE REVIEW

**Comment by adamroszyk** [comment]
It doesn't seem to work for me- I've just tested it and when changing Render mode to Shader, and then GroundtruthRenderMode to depth- nothing changes in the render view.

**Comment by jc211** [comment]
@adamroszyk Are you sure your depth data is loaded? What happens when the render mode changes? Is it a black screen?

**Comment by adamroszyk** [comment]
@jc211 Sorry, my mistake- I thought that the depth data is being generated from regular rgb inputs as well.
If I'd like to add the depth photos for the calculations- how do I go about it? Are there any specific parameters I should add/ what's the recommended photo format for it?

**Comment by Tom94** [comment]
Thank you!

**Pull request merged**
