### PR TITLE
New Docker

### PR DESCRIPTION
**Pull request by flipphillips**
Supports the new docker-compose `deploy` for nvidia containers. Also adds venv to gitignore in unrelated things that make things easier w/ vscode.

### CODE REVIEW

**Comment by flipphillips** [comment]
Just a minor change to let the docker-compose work with the new Compose ala https://docs.docker.com/compose/gpu-support/

**Comment by Tom94** [comment]
Thank you!

**Comment by Spandan-Madan** [comment]
Does this work with linux as well? I see it has a dependency of VS code, so wanted to check if this is only for windows, or also works with linux?

**Comment by flipphillips** [comment]
> Does this work with linux as well? I see it has a dependency of VS code, so wanted to check if this is only for windows, or also works with linux?

Yep. Vscode runs quite well in Linux fwiw.

**Pull request merged**
